displayName: Rewrite Body Gzip

summary: Built on top of Traefik Rewrite Body plugin to also support gzip decompress -> update -> recompress.

type: middleware

import: github.com/packruler/pretty-error

testData:
  lastModified: true
  rewrites:
    - regex: "bar"
      replacement: "foo"
